import 'package:flutter/material.dart';
import 'flutter_flow/flutter_flow_util.dart';

abstract class FFAppConstants {
  static const String visionPrompt =
      'Can you give me a list of the snacks similar to the one that is in the provided image of the snack? Find snacks of similar taste and texture profiles as well as include foreign snacks that are similar to the snack in the picture.\n\nImportant: Look for text on the snack and the image of it as well as any other descriptions on the snack that tell what it is and abide by the following json schema for storing detections. Only include the populated schema in your response. Extra Important: Put the Snack Title into variable title, Snack country of origin into variable author, and snack description in variable year. \n\n{\'\$defs\':\n {\'BookDetection\': \n{\'properties\': \n{\'title\': {\'title\': \'Title\',\'type\': \'string\'},\n\'author\': {\'title\': \'Author\', \'type\': \'string\'},\n\'year\': {\'title\': \'Year\', \'type\': \'string\'}},\n \'required\': [\'title\', \'author\', \'year\'],\n \'title\': \'BookDetection\',\n\'type\': \'object\'}},\n\'properties\': {\'books\': {\'items\': {\'\$ref\': \'#/\$defs/BookDetection\'},\n\'title\': \'Books\',\n \'type\': \'array\'}},\n \'required\': [\'books\'],\n \'title\': \'BookDetectionResult\',\n \'type\': \'object\'}\n\nImportant: If the country origin or title can\'t be found use \"Unknown\" for the respective missing value. For year, try and look it up based on the title and author.';
  static const String summarizePrompt =
      'For the provided snack could you look up the snack and provide a brief summary. Keep the overview\'s length to a couple sentences. The key ideas of the snack should be short descriptions of the most prominent findings and meanings. Limit the total number of key ideas to 3. Important: Please format your output using the following json schema. Only include the populated schema in your response. For the quotes variable, include the category the snack falls into. \n\n{\'properties\': {\'overview\': {\'title\': \'Overview\', \'type\': \'string\'},\n  \'themes\': {\'items\': {\'type\': \'string\'}, \'title\': \'Key Ideas\', \'type\': \'array\'},\n  \'quotes\': {\'items\': {\'type\': \'string\'}, \'title\': \'Quotes\', \'type\': \'array\'}},\n \'required\': [\'overview\', \'themes\', \'quotes\'],\n \'title\': \'Summary\',\n \'type\': \'object\'}\n\nSummarize the following snack: ';
}
